language: c
sudo: false

cache:
    directories:
    - $HOME/.stack

addons:
    apt:
        packages:
        - libgmp-dev

before_install:
- mkdir -p $HOME/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack setup
- stack install pandoc

script:
- git repack -ad
- stack --no-terminal --skip-ghc-check test

after_success:
- bash .ci/update_pages.sh
